"use client";
import React from 'react';
import {
  LucideProps,
  FlaskConical, Book, GraduationCap, Brain, Calculator,
  Microscope, Monitor, History, Languages, Terminal,
  Building, Palette, Music, Dumbbell, Landmark,
  Gavel, Pill, Variable, Globe, Trophy,
  Zap, Cpu, Plug, Wrench, HardHat,
  BrickWall, Rocket, LineChart, Code, Map,
  Search, Menu, Plus, Settings, Home,
  MoreVertical, Check, X, AlertCircle, Info,
  ChevronLeft, ChevronRight, ChevronDown, ChevronUp,
  User, Users, Folder, File, FileText,
  MessageSquare, Bell, Calendar, Clock,
  LogOut, Edit, Trash2, Save, Download,
  Upload, Camera, Image as ImageIcon, Link, FolderOpen,
  Mail, Phone, Shield, Lock, Unlock,
  Star, Heart, Share2, Play, Pause,
  SkipForward, SkipBack, Volume2, VolumeX,
  Maximize, Minimize, RefreshCw, Layers,
  Compass, Award, Lightbulb, Target,
  Filter, Grid, List, Layout,
  Eye, EyeOff, Key, Copy, CheckSquare,
  Square, ShieldCheck, CreditCard, ShoppingCart,
  ArrowRight, ArrowLeft, ArrowUp, ArrowDown,
  PieChart, BarChart2, Activity, Wifi,
  Smartphone, Laptop, Server, Cloud,
  Sun, Moon, UploadCloud, DownloadCloud,
  FileCode, PlayCircle, PenTool,
  Library, Video, Type, CheckCircle2, Circle,
  AudioLines, CalendarDays, Pipette, Fingerprint,
  RotateCw, Timer, Infinity, UserMinus, Link2, Link2Off,
  CalendarCheck, Megaphone, LayoutDashboard, TrendingUp
} from 'lucide-react';

const materialToLucideMap: Record<string, React.FC<LucideProps>> = {
  // Hive Icons (from NewHiveModal / Database)
  'science': FlaskConical,
  'menu_book': Book,
  'school': GraduationCap,
  'psychology': Brain,
  'calculate': Calculator,
  'biotech': Microscope,
  'computer': Monitor,
  'history_edu': History,
  'language': Languages,
  'terminal': Terminal,
  'architecture': Building,
  'brush': Palette,
  'music_note': Music,
  'fitness_center': Dumbbell,
  'account_balance': Landmark,
  'gavel': Gavel,
  'medication': Pill,
  'functions': Variable,
  'public': Globe,
  'stadium': Trophy,
  'bolt': Zap,
  'memory': Cpu,
  'electrical_services': Plug,
  'engineering': Wrench,
  'construction': HardHat,
  'foundation': BrickWall,
  'rocket_launch': Rocket,
  'analytics': LineChart,
  'code': Code,
  'map': Map,

  // Common UI Icons
  'search': Search,
  'menu': Menu,
  'add': Plus,
  'settings': Settings,
  'home': Home,
  'more_vert': MoreVertical,
  'check': Check,
  'close': X,
  'error': AlertCircle,
  'info': Info,
  'chevron_left': ChevronLeft,
  'chevron_right': ChevronRight,
  'expand_more': ChevronDown,
  'expand_less': ChevronUp,
  'person': User,
  'group': Users,
  'folder': Folder,
  'insert_drive_file': File,
  'description': FileText,
  'chat': MessageSquare,
  'notifications': Bell,
  'calendar_today': Calendar,
  'schedule': Clock,
  'logout': LogOut,
  'edit': Edit,
  'delete': Trash2,
  'save': Save,
  'download': Download,
  'upload': Upload,
  'photo_camera': Camera,
  'image': ImageIcon,
  'mail': Mail,
  'phone': Phone,
  'security': Shield,
  'lock': Lock,
  'lock_open': Unlock,
  'star': Star,
  'favorite': Heart,
  'share': Share2,
  'play_arrow': Play,
  'pause': Pause,
  'skip_next': SkipForward,
  'skip_previous': SkipBack,
  'volume_up': Volume2,
  'volume_off': VolumeX,
  'fullscreen': Maximize,
  'fullscreen_exit': Minimize,
  'refresh': RefreshCw,
  'layers': Layers,
  'explore': Compass,
  'emoji_events': Award,
  'lightbulb': Lightbulb,
  'track_changes': Target,
  'filter_list': Filter,
  'grid_view': Grid,
  'view_list': List,
  'dashboard': Layout,
  'visibility': Eye,
  'visibility_off': EyeOff,
  'vpn_key': Key,
  'content_copy': Copy,
  'check_box': CheckSquare,
  'check_box_outline_blank': Square,
  'verified': ShieldCheck,
  'credit_card': CreditCard,
  'shopping_cart': ShoppingCart,
  'arrow_forward': ArrowRight,
  'arrow_back': ArrowLeft,
  'arrow_upward': ArrowUp,
  'arrow_downward': ArrowDown,
  'pie_chart': PieChart,
  'bar_chart': BarChart2,
  'trending_up': Activity,
  'wifi': Wifi,
  'smartphone': Smartphone,
  'laptop': Laptop,
  'dns': Server,
  'cloud': Cloud,
  'light_mode': Sun,
  'dark_mode': Moon,
  'cloud_upload': UploadCloud,
  'cloud_download': DownloadCloud,
  'integration_instructions': FileCode,
  'smart_display': Video,
  'auto_awesome': Star,
  'more_horiz': MoreVertical,
  'hive': Layers,
  'arrow_outward': ArrowRight,
  'sort': Filter,
  'tag': Plus,
  'person_add': User,
  'play_circle': PlayCircle,
  'check_circle': CheckCircle2,
  'event_available': CalendarCheck,
  'event_busy': AlertCircle,
  'library_books': Library,
  'article': FileText,
  'history': History,
  'clear': X,
  'apps': Grid,
  'open_in_new': ArrowRight,
  'delete_outline': Trash2,
  'sync': RefreshCw,
  'drag_indicator': Menu,
  'arrow_drop_down': ChevronDown,
  'photo': ImageIcon,
  'picture_as_pdf': FileText,
  'videocam': Video,
  'mic': Music,
  'draw': PenTool,
  'text_fields': Type,
  'attach_file': Link,
  'folder_open': FolderOpen,
  'warning': AlertCircle,
  'task_alt': CheckCircle2,
  'radio_button_unchecked': Circle,
  'arrow_back_ios_new': ChevronLeft,
  'arrow_forward_ios': ChevronRight,
  'audio_lines': AudioLines,
  'graphic_eq': AudioLines,
  'calendar_month': CalendarDays,
  'palette': Palette,
  'colorize': Pipette,
  'progress_activity': RotateCw,
  'hourglass_empty': Timer,
  'all_inclusive': Infinity,
  'today': Calendar,
  'date_range': CalendarDays,
  'account_circle': User,
  'fingerprint': Fingerprint,
  'user_minus': UserMinus,
  'link': Link2,
  'link_off': Link2Off,
  'manage_accounts': Settings,
  'space_dashboard': LayoutDashboard,
  'subject': FileText,
  'insights': TrendingUp,
  'campaign': Megaphone,
};

export interface IconProps extends Omit<React.SVGProps<SVGSVGElement>, 'size'> {
  name: string;
  size?: number | string;
  className?: string;
}

export function Icon({ name, size, className = '', ...props }: IconProps) {
  // Try to find the exact match first
  let LucideIcon = materialToLucideMap[name];

  // If no match, try some fuzzy matching or fallback
  if (!LucideIcon) {
    if (name.includes('arrow')) LucideIcon = ArrowRight;
    else if (name.includes('file') || name.includes('document')) LucideIcon = FileText;
    else if (name.includes('user') || name.includes('person')) LucideIcon = User;
    else if (name.includes('setting') || name.includes('gear')) LucideIcon = Settings;
    else if (name.includes('check')) LucideIcon = Check;
    else if (name.includes('close') || name.includes('clear')) LucideIcon = X;
    else if (name.includes('add') || name.includes('plus')) LucideIcon = Plus;
    else if (name.includes('event') || name.includes('calendar')) LucideIcon = Calendar;
    else LucideIcon = FileText; // Default fallback
  }

  // Use "1em" as default size so it respects Tailwind text-size classes (like the old font icons)
  // but allow explicit size overrides.
  return (
    <LucideIcon 
      size={size || "1em"} 
      className={`inline-block align-text-bottom ${className}`} 
      {...props} 
    />
  );
}
